### ISSUE TITLE
set default language on chat to what was selected when user entered the website.

### ISSUE THREAD

**Issue by sean-r-martin** [adam2222/autolingo#46]

**Comment by jamesboh** [comment]
Update:
VoiceRegognitionContainer line 128
"recognition.lang = select_dialect.value;” has changed to "recognition.lang = props.userDialect” where props.userDialect is passed in from mapStateToProps from the store so it’s basically a matter of updating ‘userDialect’ in the store when you choose a language, which can be done with a combination of language and country using the array in data/languages.js
